# swagger.yml

openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API about people and notes"
  version: "2.0.0"

servers:
    - url: "/api"

components:
  schemas:
    Person:
      type: "object"
      required:
        - lname
      properties:
        fname:
          type: "string"
        lname:
          type: "string"
    Note:
      type: "object"
      required:
        #a note cannot exist without a person nor a content
        - person_id
        - content
      properties:
        content:
          type: "string"
        person_id:
          type: "integer"
  parameters:
    lname:
      name: "lname"
      description: "Last name of the person to get"
      in: path
      required: True
      schema:
        type: "string"
    noteid:
      name: "noteid"
      description: "id of the note to get"
      in: path
      required: True
      schema:
        type: "integer"

paths:
  /people:
    get:
      operationId: "people.read_all"
      tags:
        - "People"
      summary: "Read the list of people"
      responses:
        "200":
          description: "Successfully read people list"
    post:
      operationId: "people.create"
      tags:
        - "People"
      summary: "Create a person"
      requestBody:
        description: "Person to create"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "person"
              $ref: "#/components/schemas/Person"
      responses:
        "201":
          description: "Successfully created person"
  /people/{lname}:
    get:
      operationId: "people.read_one"
      tags: 
        - People
      summary: "Read one person"
      parameters:
        - $ref: "#/components/parameters/lname"
      responses:
        "200":
          description: "Successfully read person"    
    put:
      operationId: "people.update"
      tags: 
        - People
      summary: "Update one person"
      parameters:
        - $ref: "#/components/parameters/lname"
      responses:
        "200":
          description: "Successfully updated a person"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "person"
              $ref: "#/components/schemas/Person"
    delete:
      tags:
        - People
      operationId: "people.delete"
      summary: "Delete a person"
      parameters:
        - $ref: "#/components/parameters/lname"
      responses:
        "204":
          description: "Successfully deleted person"
  /notes:
    get:
      operationId: "notes.read_all"
      tags:
        - "Note"
      summary: "Read the list of note"
      responses:
        "200":
          description: "Successfully read note list"
    post:
      operationId: "notes.create"
      tags:
        - "Note"
      summary: "Create a note associated with a person"
      requestBody:
          description: "Note to create"
          required: True
          content:
            application/json:
              schema:
                x-body-name: "note"
                $ref: "#/components/schemas/Note"
                # type: "object"
                # properties:
                #   person_id:
                #     type: "integer"
                #   content:
                #     type: "string"
      responses:
        "201":
          description: "Successfully created a note"
  /notes/{noteid}:
    get:
      operationId: "notes.read_one"
      tags: 
        - Note
      summary: "Read one note"
      parameters:
        - $ref: "#/components/parameters/noteid"
      responses:
        "200":
          description: "Successfully read note" 
    put:
      operationId: "notes.update"
      tags: 
        - Note
      summary: "Update one note"
      parameters:
        - $ref: "#/components/parameters/noteid"
      responses:
        "200":
          description: "Successfully updated a note"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "note"
              $ref: "#/components/schemas/Note"
    delete:
      tags:
        - Note
      operationId: "notes.delete"
      summary: "Delete a note"
      parameters:
        - $ref: "#/components/parameters/noteid"
      responses:
        "204":
          description: "Successfully deleted note"